spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri:
              lb://USER-SERVICE
            predicates:
              - Path=/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
